//Crear usuario
export const REGISTRAR_USUARIO_NUEVO = "REGISTRAR_USUARIO_NUEVO";
export const REGISTRAR_USUARIO_EXITO = "REGISTRAR_USUARIO_EXITO";
export const REGISTRAR_USUARIO_ERROR = "REGISTRAR_USUARIO_ERROR";

//Iniciar sesion
export const LOGIN_USUARIO_NUEVO = "LOGIN_USUARIO_NUEVO";
export const LOGIN_USUARIO_EXITO = "LOGIN_USUARIO_EXITO";
export const LOGIN_USUARIO_ERROR = "LOGIN_USUARIO_ERROR";
