//Types Auth
export const REGISTER_NEW_USER = "REGISTER_NEW_USER";
export const REGISTER_EXIT_USER = "REGISTER_EXIT_USER";
export const REGISTER_ERROR_USER = "REGISTER_ERROR_USER";
export const OBSERVER_USER = "OBSERVER_USER";

//Types Address
export const LOADING = "LOADING";
export const ADD_ADDRESS_ERROR = "ADD_ADDRESS_ERROR";
export const GET_ADDRESS = "GET_ADDRESS";
